### ISSUE TITLE
Example fails to build

### ISSUE THREAD

**Issue by woo2** [boldport/hello-solder#2]
PCBmodE was installed from git with ``$ python setup.py install``

pcbmode_config.json has not been changed

Python: 2.7.11
PyParsing: 2.1.5
lxml: 3.4.4

When I run ``$ pcbmode -b hello-solder`` I get:
```
-- Processing PCBmodE's configuration file
-- Processing board's configuration file
-- Done!
```

But, when I make the board with ```$ pcbmode -b hello-solder -m```, there is an error:

```
-- Processing PCBmodE's configuration file
-- Processing board's configuration file
-- Creating board
Traceback (most recent call last):
  File "/usr/bin/pcbmode", line 9, in <module>
    load_entry_point('pcbmode==4.1.dev19+ng1b4456b', 'console_scripts', 'pcbmode')()
  File "build/bdist.linux-x86_64/egg/pcbmode/pcbmode.py", line 379, in main
  File "build/bdist.linux-x86_64/egg/pcbmode/utils/board.py", line 21, in __init__
  File "build/bdist.linux-x86_64/egg/pcbmode/utils/module.py", line 58, in __init__
  File "build/bdist.linux-x86_64/egg/pcbmode/utils/module.py", line 960, in _getComponents
AttributeError: 'list' object has no attribute 'get'
```

My Directory Structure:
```
pcbs/
└── pme
    ├── boards
    │   └── hello-solder
    │       ├── build
    │       │   ├── images
    │       │   └── paths_db.json
    │       ├── components
    │       │   ├── 0805.json
    │       │   ├── 10mm-led.json
    │       │   ├── flower-pad.json
    │       │   ├── hole-3p1mm.json
    │       │   └── via.json
    │       ├── hello-solder.json
    │       ├── hello-solder_routing.json
    │       ├── LICENSE
    │       └── README.md
    ├── files
    ├── fonts
    │   ├── Aaargh-webfont.svg
    │   ├── FascinateInline-Regular-webfont.svg
    │   ├── GoodDog-Regular-webfont.svg
    │   ├── Helsinki-webfont.svg
    │   ├── Lato-Reg-webfont.svg
    │   ├── Overlock-Regular-OTF-webfont.svg
    │   ├── Pacifico-webfont.svg
    │   ├── Snickles-webfont.svg
    │   └── UbuntuMono-R-webfont.svg
    ├── pcbmode_config.json
    ├── stackups
    │   ├── four-layer.json
    │   └── two-layer.json
    └── styles
        └── default
            └── layout.json
```

**Comment by saardrimer** [comment]
That repo was for PCBmodE 3.0, and is not compatible with PCBmodE 4.0, which is the latest version.
Try a more recent design.

**Comment by woo2** [comment]
Ahh, I did not notice that the current version is 4. Thanks.
